GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic2FiZXIiLCJpZCI6MSwiaWF0IjoxNTkxMzYyMjM4fQ.fldH0YoENiRkYiol91SheNHASWqmqjWzAD_pdLd2xa4

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username":"saber",
    "id":1
}